str1 = input("Enter First String to concatenate: ")
str2 = input("Enter Second String to Concatenate : ")
con = str1 + str2
print(con)
print(con.lower())
print(con.upper())
print(con.swapcase())
print(con.capitalize())
print(con.casefold())
print(con.center(50))
print(con.count("h"))
print(con.endswith("o"))
print(con.find("h"))
print(con.isalnum())
print(con.isdigit())
print(con.isnumeric())
print(con.isspace())
print(con.replace("hello", "world"))